### ISSUE TITLE
New include syntax not working in with debug

### ISSUE THREAD

**Issue by samary** [quattor/template-library-core#105]
Hi,

I tried to build a scdb-vanilla from this repo but this commit (d60221fab7f2c360b74c8a7015a9c22887c326ad) introduced some syntax error : 

```
[panc-check-syntax] parse error [/tmp/scdb-vanilla/cfg/quattor/dev/quattor/aii/ks/config.pan:405.112-405.405]
[panc-check-syntax] 
[panc-check-syntax] Encountered: AII_KS_OS_MAJOR_SPECIFIC_INCLUDE
```

Problematic lines are : 
https://github.com/quattor/template-library-core/blob/d60221fab7f2c360b74c8a7015a9c22887c326ad/quattor/aii/ks/config.pan#L392
https://github.com/quattor/template-library-core/blob/d60221fab7f2c360b74c8a7015a9c22887c326ad/quattor/aii/ks/config.pan#L399

Removing the debug or using curly-braces fixes the issue.

I'm wondering how this pull request has been merged without any check (build or check syntax).
I suggest every new pull request should build the scdb-vanilla script (from scdb repo) and block the merge in case of compilation issue.

**Comment by stdweird** [comment]
this was caught by the unittests https://jenkins1.ugent.be/view/Quattor/job/template-library-core-pr-builder/109/console, but the release process which merges pan templates from around the repos in one doesn't honour the tests (which is fine), but the state of the master https://jenkins1.ugent.be/view/Quattor/job/template-library-core/9/ should be checked.

**Comment by stdweird** [comment]
also this specific bug is already fixed in aii (and template library-core master). the unittest failure is due to something else.

**Comment by jrha** [comment]
@samary this snuck in due to @jouvin's PR (#100) having a horrible mess of conflicts, I missed the AII changes (which should have been made to https://github.com/quattor/aii), but in any case these should have since been overwritten by the changes in quattor/aii#159 as part of the 16.2.0-rc1 release process.

**Comment by jrha** [comment]
Can you run again with the tagged templates for rc1 please, because this issue should not exist in them.
