### ISSUE TITLE
remove get_subnet_params from quattor/functions/network

### ISSUE THREAD

**Issue by stdweird** [quattor/template-library-core#149]
Esp if it is not used anywhere.
It claims to be `This is a 'dirty solution' to work around the lack of bitwise AND in pan... `, which exists in pan.

**Comment by stdweird** [comment]
i grepped our repos, no hits except the definiton itself

**Comment by jrha** [comment]
Yes, but only in our crumbly old SCDB, feel free to remove it.

**Comment by stdweird** [comment]
reintroduced in #154, wa sin use at LAL
