### ISSUE TITLE
Revert os and model fields structure archetype to Aquilon standard

### ISSUE THREAD

**Issue by ned21** [quattor/template-library-core#179]
In #142 we tried to remove some of the MS specific terms used for OS versions and implement a more logical structure. This was done on the supposition that:

1.  There was no dependency on those fields from shared parts of the project. This was proven untrue by the discover of the dependency on /system/archetype/name in [ncm-cron](https://github.com/quattor/configuration-modules-core/issues/1281).
1. The structure was populated only by templates and thus individual sites were free to use whatever format they wish. This turned out to be incorrect since the previous October the broker had been changed to populate those fields.

At the time I thought we might be able to adopt the new structure but that subsequently also proven impossible, not only because the broker is now populating those fields which makes it a significant undertaking for us to change, but also because that version field is so important it's consumed as part of our data warehouse code. Combined, these factors mean that changing the field would require a significant coordinated change across multiple code bases and probably downtime so it's not going to happen.

Also subsequently, @jouvin has started to advocate having the broker populate more items in the templates, thus further negating (2) above. In order for this approach to work, the broker and templates **must be** aligned to avoid divergent code paths that are time consuming to maintain and cross-communication issues between the primary broker developers and community users. 

I am cognisant that in encouraging the change in #142 I made a significant error in judgement for which I apologise. I believe that at present only 1 site is effected, @jrha since the three others sites using Aquilon are on more recent versions of Aquilon where the prior structures are now required.

@jrha : how painful would it be for you to back out of this and use an alternative structure?

**Comment by jrha** [comment]
Superficially I don't think it will cause us too much pain, but I will have to look carefully at what people have built since the change was made.

In theory we are only making use the structure under '/system/os' that #142 was originally designed for.

**Comment by jrha** [comment]
Actually, we can revert it, a quick scan of our profiles shows that no-one is populating anything other than `/archetype/name`.

**Comment by ned21** [comment]
@jrha - thanks. I owe you :beer:
