### ISSUE TITLE
provide `structure_monitoring`

### ISSUE THREAD

**Issue by stdweird** [quattor/template-library-core#59]
the current `stucture_system` has an optional `monitoring` attribute with type `structure_monitoring`. This type however is not provided as part of this repo, and most likely comes from from the `include 'quattor/monitoring/lemon';`, which is also not part of this repository.

**Comment by jouvin** [comment]
@loomis Any comment on this?

**Comment by samary** [comment]
Any update about this issue ? As we are not using the monitoring repository, we have to comment this line at each template update. Does someone have a proposal to fix this ?

**Comment by ned21** [comment]
For reference this is this [line](https://github.com/quattor/template-library-core/blob/master/quattor/types/system.pan#L30) and this [line](https://github.com/quattor/template-library-core/blob/master/quattor/types/system.pan#L53). If lemon is dead then we can probably just fix do this:

```include { if_exists('monitoring/lemon/schema') };```

but that will still cause the second to fail so we just replace it with a generic nlist.

```type structure_system = {
   ...
   "monitoring"    ? nlist
};
```

If you still use /system/monitoring and want to validate it then you an still do this:
```bind /system/monitoring = structure_monitoring;```

but there is no way with a bind to specify an optional type, bind will convert "? nlist" to ": structure_monitoring". :(

Is anyone still using lemon for whom this would actually be a breaking change?

**Comment by jouvin** [comment]
@ned21 thanks for this proposal, we have been looking how to do it for years! I think `/system/monitoring` was used with Nagios too but I may be wrong...

Commenting on the implementation in [PR](#125).

**Comment by jrha** [comment]
"Fixed" in #125 by removing the type and allowing monitoring templates to bind their own type to the schema.
