### ISSUE TITLE
quattor-client: remove extra dependencies

### ISSUE THREAD

**Issue by jrha** [quattor/template-library-core#65]
As noted in quattor/release#90 we include extra packages on quattor clients.
In this repository this is handled by `quattor/client/rpms.pan`.

These are:
- yum-priorities (xL5)
- yum-plugin-priorities (! xL5)
- yum-plugin-versionlock
- perl-AppConfig
- python-elementtree (xL5)

We should add these as dependencies of the things that need them and remove them from this template.

**Comment by jouvin** [comment]
For me this isssue has been fixed a while ago (May 18, 2015) by @stdweird. #114 is a minor cleanup to use `pkg_repl` and handle properly the version locking used anywhere else in the Quattor client (e.g. configuration modules).
I suggest closing this issue, except if I missed something. @jrha any comment?

**Comment by jrha** [comment]
Are they dependencies now expressed correctly by the RPMs?

**Comment by jouvin** [comment]
@jhra I just had a quick check on a SL6 machine with 16.12 and yes, the dependencies are correctly expressed in the RPMs. And as I said the mentioned template has been cleaned up a while ago. I really think this issue can be closed.

**Comment by jrha** [comment]
Great, thanks!
