### ISSUE TITLE
is_fqdn function also matches partially qualified hostnames

### ISSUE THREAD

**Issue by gvasilak** [quattor/template-library-core#66]
The [`is_fqdn`](https://github.com/quattor/template-library-core/blob/master/pan/types.pan#L431) function in [types.pan](https://github.com/quattor/template-library-core/blob/master/pan/types.pan) will match partially qualified hostnames as well as proper FQDNs.
For instance, it will match `example.org` (which it should) but will also match `example`.
The [regex](https://github.com/quattor/template-library-core/blob/master/pan/types.pan#L436) will match a properly formed hostname component followed by a literal `.` or the end of the string.

This means there is no functionality available to ensure that a value is actually an FQDN as opposed to a hostname.

Furthermore, the [`is_hostname`](https://github.com/quattor/template-library-core/blob/master/pan/types.pan#L448) function seems to [rely](https://github.com/quattor/template-library-core/blob/master/pan/types.pan#L453) on this behaviour (it should match IPs, FQDNs and partially qualified hostnames) and would be (partially) broken by a fix to `is_fqdn`.

**Comment by jrha** [comment]
Thanks for spotting this!

**Comment by gvasilak** [comment]
A quick look through the net has yielded this:
`(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}\.?$)`
which isn't perfect but I think it's better.
It uses negative lookaheads and lookbehinds to make sure no _label_ starts or ends with a `-`, enforces a minimum of two labels, the last of which should be at least two characters long (no currently accepted TLDs have fewer than two characters) and will accept a trailing dot (for the root domain).

Caveats I can immediately see:
1. If there is a trailing dot and the rest is still 253 characters it will match but the FQDN will be longer than 255 **octets** and thus non-conformant to the standard.
2. It won't match FQDNs like `example.` which could be valid directly under the root domain (although highly likely to ever be used).

**Comment by jrha** [comment]
@gvasilak could you open a PR to update the regexp?
