### ISSUE TITLE
Add helper function to create a biosboot partition

### ISSUE THREAD

**Issue by jrha** [quattor/template-library-core#72]
Add a function to add a biosboot partition with the `bios_boot` flag set, perhaps `mkbiosboot`?
As discussed in quattor/ncm-lib-blockdevices#49

**Comment by jouvin** [comment]
After merging https://github.com/quattor/template-library-core/issues/126 and https://github.com/quattor/template-library-standard/issues/85, this issue can be closed.

**Comment by jrha** [comment]
Fixes were merged for 16.10, milestone corrected.
